apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.Namespace.name }}
{{- include "charts.lables" $ | indent 2 }}
spec:
  type: NodePort 
  ports:
  - port: 80
    targetPort: 80
    nodePort: {{ .Values.ingress.port.nodePort }}
    protocol: TCP
    name: http
{{- include "charts.selector" $ | indent 2 }}